### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ebogucka** [jarhill0/PocketRSS#1]
Dear @jarhill0,

I like your project and would like to use it, but I have noticed that it does not have a LICENSE file. Could you please specify the license for this project? This [page](https://choosealicense.com/no-permission/) explains why it is needed.

**Comment by jarhill0** [comment]
Hi, and thanks for your interest @ebogucka! I'll add a license.

As you can see from the commit history, I haven't touched this project in about a year and a half. I do have aspirations for how this can be better (multiple users, web interface in Flask), but realistically this isn't a high priority for me.
